server:
  port: 8089
spring:
  application:
    name: dsf-center-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dsf_center_master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: xuyun1225
    username: root
#    username: ryan
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#redis conf
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        min-idle: 1
        max-wait: 300
    database: 10

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${eureka.instance.appname}
    appname: dsf-center-service-01
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
#  configLocation: classpath:mybatis.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    interceptors:
#      - com.invech.platform.dsfcenterdao.config.MybatisInterceptor

mapper:
  mappers:
    - com.invech.platform.dsfcenterdao.config.MybatisAutoMapper
#驼峰转下划线
  style: camelhumpandlowercase
  not-empty: false
  identity: MYSQL



#  swagger 开关 http://localhost:8089/swagger-ui.html
swagger:
  profile: dev
  scope: com.invech.platform.dsfcenterservice.controller