server:
  port: 8081

spring:
  application:
    name: dsf-center-service

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
logging:
  level: debug