spring:
  profiles:
    active: dev

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${eureka.instance.appname}
    appname: dsf-center-service-01
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/
#mybatis:
#  mapperLocations: classpath:mapper/**/*.xml
#  configLocation: classpath:mybatis.xml

#mapper:
#  mappers:
#    - com.invech.platform.dsfcenterdao.mapper
#  style: normal
#  not-empty: false
#  identity: MYSQL

logging:
  config: classpath:logback-admin.xml

log:
  level:
    root: info
    mylog: debug
  file: ./log/dsf-center-service.log
  maxsize: 60MB
